### ISSUE TITLE
Please allow up to four parameters for --titlefont, --messagefont

### ISSUE THREAD

**Issue by bradtchapman** [bartreardon/swiftDialog#127]
We have a corporate standard font installed on every Mac, and a standard corporate colo(u)r palette.  I would like to use titlefont to set the color, size, font family AND weight all at once.  With only three options, I will need to compromise on size, weight, or color.

Please allow all four parameters to be used.  Thanks!

**Comment by bradtchapman** [comment]
Unintended workaround, possible bug:

The 'weight' option doesn't appear to do anything here (or yet).
However, the "name" field accepts both the "PostScript Name" and "Full Name" of a given font / weight. 

# This results in SF Pro Regular
dialog -d -t "ACME Corp Software Updates" --titlefont size=24,name=SFPro,weight=heavy
dialog -d -t "ACME Corp Software Updates" --titlefont size=24,name=SFPro,weight="heavy"
dialog -d -t "ACME Corp Software Updates" --titlefont size=24,name="SF Pro",weight=light

# Results in SF Pro Heavy:
dialog -d -t "ACME Corp Software Updates" --titlefont size=24,name=SFPro-Heavy
dialog -d -t "ACME Corp Software Updates" --titlefont size=24,name="SF Pro Heavy"

# Results in SF Pro Light:
dialog -d -t "ACME Corp Software Updates" --titlefont size=24,name="SF Pro Light"

**Comment by bartreardon** [comment]
Due to how the title font stuff is written, weight only takes effect when not specifying the font. To change the weight of specified font you need to use the full font name, as you discovered `SFPro-Heavy` or the like.

`--listfonts` will list out all the names that will be recognised. This may match the names in font book or it might be different.

There are optimisations that can be made though.
