### ISSUE TITLE
Localization for Messaging

### ISSUE THREAD

**Issue by joncrain** [bartreardon/swiftDialog#140]
Would like the ability to natively handle the localization of messages based on the users language choice. 

For example, if a user chooses the French language, the text options would have values like `-message` & `-messageFR` or `-title` & `-titleFR` and swiftDialog could correctly determine which message takes precedence. 

This understandably could potentially create a mess of spaghetti code especially as more languages would be added/created, so if this is not the proper solution, then this can be handled in the script code.

**Comment by bartreardon** [comment]
I've had a think about it and I don't think language support within the app itself is something I want to work with. There is localisation for in-app elements such as default button labels etc but as titles and messages are defined by the admin then there's going to be a bunch of work on the admin side anyway to support multiple languages.

One way to achieve this in script :

```bash
language=$(locale | grep LANG | awk -F '=' '{print $NF}' | tr -d '"')

case ${language} in
en*)
    echo "English"
    ;;
fr*)
    echo "French"
    ;;
de*)
    echo "German"
    ;;
*)
    echo "Default"
    ;;
esac

```

You then set your dialog variables based on what language is detected.

Since an admin would have to create all these cases anyway to provide the various languages, adding in a case statement to use the correct one would be trivial.
