### ISSUE TITLE
Mini window does not respect `--title none`

### ISSUE THREAD

**Issue by scriptingosx** [bartreardon/swiftDialog#155]
This is for 1.11.2 preview 2 (2988).

When you create a mini window with `--title none` the window title will be a literal 'none'

<img width="652" alt="image" src="https://user-images.githubusercontent.com/1933192/183978991-e0d076b3-749c-4739-8873-e7d1a27412b5.png">

It would be better if this showed no title, like with the normal window size.

**Comment by bartreardon** [comment]
@scriptingosx how does this look?

in addition to accepting `--title none`, I've re-done how the mini window is displayed entirely so you now get more lines of text. It is slightly taller as a result (128 instead of 125)

Here's some screenshots of how the mini window looks with various text and modes

![image](https://user-images.githubusercontent.com/3598965/184052471-1cb96c0c-95a3-4776-97b1-a239c792d960.png)

**Comment by bartreardon** [comment]
small update to the button position so it's not so close to the text (if it ever gets that long)
![image](https://user-images.githubusercontent.com/3598965/184065191-46ed6120-825b-486d-ba8d-3b2f42bfa627.png)

**Comment by bartreardon** [comment]
and another for the text padding 

![image](https://user-images.githubusercontent.com/3598965/184065673-e18a3507-d836-4496-ad4f-54dcfc909d12.png)

**Comment by scriptingosx** [comment]
Looks great, thank you!
