### ISSUE TITLE
2.0 Preview.3663: `message:` not updating in `--mini`mode

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#174]
When using `--mini`mode in `2.0 Preview.3663`, `message` isn't updated on-the-fly as expected.

https://user-images.githubusercontent.com/24623109/195954687-7063ed32-0784-4bbd-abe5-fc0540eb7f13.mp4

**Comment by bartreardon** [comment]
yup, known issue with the command file processing. I suspect this is an bug with xcode 14.0.1 that has incorrect thread handling. I need to test a version compiled against Xcode 13

**Comment by dan-snelson** [comment]
Appears to be resolved in `2.0 Preview.3706`; thanks!

<img width="652" alt="Screen Shot 2022-10-15 at 3 26 08 AM" src="https://user-images.githubusercontent.com/24623109/195981602-5eb11585-e557-4b0b-9ce2-f09d38130667.png">

<img width="608" alt="Screen Shot 2022-10-15 at 3 26 17 AM" src="https://user-images.githubusercontent.com/24623109/195981616-1f1a90d1-a861-47ec-b0c0-f703cda1595c.png">

**Comment by bartreardon** [comment]
Turns out I was wrong. I was not referencing the correct value for the message when in mini view. (some inside baseball, the mini view is essentially a completely different implementation of the dialog window, not just a "preset" or something. So everything it does is duplicated and if I change a reference for the full dialog window, I have to remember to change it here as well. keeping it super cut down a specialised helps with that)

**Comment by dan-snelson** [comment]
Ah … good to know.

(So, what I hear you saying is that Mike and I should open new issues for the layout of `--mini` mode.)
