### ISSUE TITLE
Issues updating list items using Version 2 Preview 2

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#176]
I just started using the newest preview release, Preview 2 of the 2.0 version of swiftDialog, and I'm seeing issues that I was also seeing in the previous preview release.
Specifically, I have a patch script where I use swiftDialog to update a List with status and use the new progress bar icon. What I'm seeing is that my script (which worked perfectly with the older 1.x version) properly moves the list items icon from Pending to Updating, but fails to move from that stage, so I end up with a bunch of completed progress bar icons, none of them showing the checkmark  icon (status: success) nor the status text saying "Complete", despite my script instructing swiftDialog to do that.

Also, the main progress bar at the bottom of the screen is supposed to progress thru several steps that are equal to the number of stages in the installations, but remains in an "indeterminate" progress bar the entire time the script is running.

Lastly, the button stays grayed out during the installs and then at the end should change to "Done", but remains with the text "Please wait"

It's almost like it's not respecting the commands I'm pushing to the command file. Or only part of the commands and ignoring ones later in the script.

I've attached a screenshot showing an example of this. As you can see the status text does not get updated, nor does the icon or main button as they all should.

<img width="435" alt="Screen Shot 2022-10-19 at 8 56 18 AM" src="https://user-images.githubusercontent.com/3653600/196701251-5364b789-9912-462d-97a6-9f6671ae7c86.png">

**Comment by dan-snelson** [comment]
@mm2270: I have yet to test the latest preview; do you happen to already have the “minimum delay of 0.03 seconds between sending commands to the command file.” ?

**Comment by mm2270** [comment]
Hi @dan-snelson I do have pauses between most sends to the command file, but I will see if by chance some of them are being written to it too quickly. That could be it, I guess. I'll go through my script and make sure there is at least that much of a delay between each command and try it again and report back.

**Comment by bartreardon** [comment]
This will most certainly be a result of sending commands to the command file quicker than can be registered. The reason for this is the method used to read in the file has been replaced with a (mostly) pure swift rather than forking a shell process. It will trigger a read notification when the file is updated and then read in the last line. If you add a new command faster than what can be read in you could be reading in the wrong line entirely. 

I'd recommend adding a short delay of at least 0.03 sec which can be implemented with the following short function:

```bash
updatedialog() {
    /bin/echo "$1" | tee -a /var/tmp/dialog.log
    sleep 0.03
}
```

and then you can run that command with `updatedialog "command: here"`

**Comment by martinvandiemen** [comment]
Could the delay be added to swift instead of the script? When startup up swiftDialog I noticed that I have to delay up to 1 second before the list can be added to the command file (version 1). It would be nice if this would be handled by the app. Maybe the app can read the file more often and just monitor is the last line has changed before processing.

**Comment by Lotusshaney** [comment]
Getting the same problem with a simple progresstext and a command file.  Tried a delay up to 1 seconds and sometimes it sill misses the updates to the command file.  Sometimes the miss items will be applied after the next update hits

**Comment by mm2270** [comment]
Adding the above function to my script and replacing any of the `echo "command: here"` calls with calling the function did help, but not completely.
I was still having a few odd issues, such as the button 1 text not getting updated at the end. I found I had to switch around the order to get it to work. I was changing the text of the button before enabling it, and that wasn't working. The button text remained at "Please wait". Once I switched it to enable the button first, then change the text that seemed to work. Strange that it would matter, but it did, at least in my case.

I guess it's going to be a matter of trial and error to get the right order and timing for any scripts to update the elements of a running dialog properly.

**Comment by bartreardon** [comment]
> Could the delay be added to swift instead of the script? When startup up swiftDialog I noticed that I have to delay up to 1 second before the list can be added to the command file (version 1). It would be nice if this would be handled by the app. Maybe the app can read the file more often and just monitor is the last line has changed before processing.

Not really - that would only exacerbate things. The command file is really designed to be used for updates to an existing dialog, so for your initial list, generate a bunch of command line arguments or json then call swiftDialog with that initial state, then start updating. 

It's an area that I'm working on to improve and why I'm releasing previews and not betas. For now though, I'm recommending a short delay in order to guarantee the commands get sent so you can at least play with v2 and all the other features. I'm just trying to set expectations, this isn't a final product.
