### ISSUE TITLE
Feature Request: `--notification --icon` to replace Dialog's icon

### ISSUE THREAD

**Issue by dan-snelson** [bartreardon/swiftDialog#181]
When testing the `--notification` feature of `2.0 Preview.3789`, the hope was that specifying a local `--icon` would replace the default Dialog icon, not display a **second** icon.

<img width="370" alt="Screen Shot 2022-10-29 at 6 44 37 AM" src="https://user-images.githubusercontent.com/24623109/198832852-f1574058-bae4-40be-9f78-35045573622e.png">

(How is Jamf pulling this off with Self Service?)

**Comment by bartreardon** [comment]
As described in Slack, This request can't be done. Apple forces notifications to have the icon of the app that created it. This is to prevent apps from spoofing other app notifications. Im looking at a munki-rebrand type thing but that will require a developer account etc.

In order to have a branded icon you will need to re-compile swiftDialog with your own image assets as the app icon.
