### ISSUE TITLE
FR - popup window option for More Information Button

### ISSUE THREAD

**Issue by mvdbent** [bartreardon/swiftDialog#190]
Is it possible to have the option of a popup window for the "More Information Button"
sometimes you have a full-screen message where you want to add more info however not on the mean message.
if we have the option to configure the more info button to have a popup window where this extra info is added.
hope this makes sense otherwise happy to add more context.

**Comment by bartreardon** [comment]
How does something like this look?

specify `--helpmessage` and supply a message in standard markdown format. Will render a question-mark button in the top right. Clicking it will display a sheet with your message.

![image](https://user-images.githubusercontent.com/3598965/206881913-7a55cfdf-0c7b-4c8e-b16a-f71e2487f1a3.png)

**Comment by dan-snelson** [comment]
Noice!

**Comment by mvdbent** [comment]
That is looking great!
And will work perfectly for full screen mode and with always on top!
Thanks for this!

**Comment by dan-snelson** [comment]
One word: Sweetness

<img width="932" alt="Screenshot 2023-01-10 at 3 25 19 AM" src="https://user-images.githubusercontent.com/24623109/211526601-6dd9c463-b6e8-4564-8ee3-918014e05f5a.png">

**Comment by dan-snelson** [comment]
@bartreardon:

Is it possible to **NOT** give focus to `--helpmessage` ?

<img width="932" alt="Screenshot 2023-01-18 at 5 17 16 PM" src="https://user-images.githubusercontent.com/24623109/213339134-e581a96e-ad60-4975-b775-79113b05e74d.png">

**Comment by bartreardon** [comment]
it doesn't - what version are you running? (and is this macos 11,12 or 13?)

**Comment by dan-snelson** [comment]
Bart:

Thanks for the screenshots; here's what I'm observing:

<img width="932" alt="Screenshot 2023-01-19 at 1 25 26 AM" src="https://user-images.githubusercontent.com/24623109/213392453-195defd3-135b-47e4-9e35-10208d9e4fe9.png">

<img width="932" alt="Screenshot 2023-01-19 at 1 25 54 AM" src="https://user-images.githubusercontent.com/24623109/213392487-3b795c39-4886-45d2-8408-95bab9bfffae.png">

Testing with Ventura …

```
Macs-MacBook-Air:tmp root# sw_vers
ProductName:	macOS
ProductVersion:	13.1
BuildVersion:		22C65

Macs-MacBook-Air:tmp root# dialog --version
2.1.0.4035
```

… and [Setup Your Mac v1.7.0-rc1](https://github.com/dan-snelson/dialog-scripts/blob/development/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash)

**Comment by bartreardon** [comment]
in [line 133](https://github.com/dan-snelson/dialog-scripts/blob/abb1a0dcd8eb7c899fbbed69406afac37d2a1ecd/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L133) if I change that from calling the app bundle binary directly to `/usr/local/bin/dialog` it works fine.

In testing the issue seems to be that when running swiftDialog as root, it's not honouring the `focusable` setting. On lines [1481](https://github.com/dan-snelson/dialog-scripts/blob/abb1a0dcd8eb7c899fbbed69406afac37d2a1ecd/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L1481) and [1515](https://github.com/dan-snelson/dialog-scripts/blob/abb1a0dcd8eb7c899fbbed69406afac37d2a1ecd/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash#L1515) the way you are calling `dialogSetupYourMacCMD` with the current value of `dialogApp` will result in swiftDialog being run as root.

This is why `/usr/local/bin/dialog` has been re-written to force swiftDialog to always run as the user as running gui apps in a user session as root introduces weirdness.

**Comment by dan-snelson** [comment]
Thanks for the detailed review, Bart.

[Setup Your Mac v1.7.0-rc2](https://github.com/dan-snelson/dialog-scripts/commit/9eb2d760549e021c36476b1193ef4873caa1e829) reverts to using pre-`1.6.0`'s:
- `dialogBinary="/usr/local/bin/dialog"`

Instead of `1.6.0`'s
- `dialogApp="/Library/Application\ Support/Dialog/Dialog.app/Contents/MacOS/Dialog"`

However, I'm still observing  `--helpmessage` receiving focus when testing locally and first elevating Terminal to `root` and then executing SYM (to simulate my current understanding of how SYM will be executed via Self Service).

<img width="932" alt="Screenshot 2023-01-20 at 2 05 23 AM" src="https://user-images.githubusercontent.com/24623109/213659513-03f3ff52-9075-45d8-9f81-6762617830d9.png">

**Comment by dan-snelson** [comment]
Elevating a user's Terminal via `sudo bash ~/Desktop/Setup-Your-Mac-via-Dialog.bash` also results in `--helpmessage` receiving focus.

<img width="932" alt="Screenshot 2023-01-20 at 2 25 41 AM" src="https://user-images.githubusercontent.com/24623109/213661397-d2e86df7-7658-4ebd-bce1-4e2d31d00321.png">

**Comment by dan-snelson** [comment]
[Setup Your Mac v1.7.0-rc3](https://github.com/dan-snelson/dialog-scripts/commit/8f3b603a0c27e4dcd0a20542a367d94260b51378) comments-out the requirement that the script be run as `root`.

When the logged-in user executes `bash ~/Desktop/Setup-Your-Mac-via-Dialog.bash` in Terminal, `helpmessage` does **NOT** receiving focus:

<img width="932" alt="Screenshot 2023-01-20 at 2 33 24 AM" src="https://user-images.githubusercontent.com/24623109/213663446-2a709130-05de-4c81-9673-0a93b9c90d1e.png">

**Comment by dan-snelson** [comment]
However, when SYM `1.7.0-rc3` is executed as `root` — to simulate how Jamf Pro will execute the script — `helpmessage` receives focus.

`root# bash /Users/dan/Desktop/Setup-Your-Mac-via-Dialog.bash`

<img width="932" alt="Screenshot 2023-01-20 at 2 40 30 AM" src="https://user-images.githubusercontent.com/24623109/213664476-2e0a5bf5-2429-498a-9490-c130ef3fc64e.png">

**Comment by dan-snelson** [comment]
Would moving `helpmessage` to the upper, left-hand corner (à la Nudge) then give focus to `button1` ?

<img width="932" alt="Screenshot 2023-01-20 at 2 40 24 AM" src="https://user-images.githubusercontent.com/24623109/213665625-f6c2c946-27ba-4931-87b6-01559fac1f50.png">

**Comment by bartreardon** [comment]
I'm not seeing any of this behaviour here. I have a terminal, logged in as root. The only line I've changed is 133 to use `/usr/local/bin/dialog` and I'm not getting the issue where the help icon is focused, unless swiftDialog runs as root instead of the user. Can you confirm in Activity Monitor what user owns the Dialog process while it's running?

Re the location, it is in line with the [HIG](https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/buttons) on where a help button (if displayed) should be
![image](https://user-images.githubusercontent.com/3598965/213685759-0bfbbce8-dd3b-4e51-9bf9-012d9dd39add.png)

**Comment by dan-snelson** [comment]
TIL; thanks for knowing — and adhering to — Apple's HIG.

I've created a [screencast](https://vimeo.com/791232918) on an un-enrolled VM with [1.7.0-rc3](https://github.com/dan-snelson/dialog-scripts/blob/development/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash). (Use this `issue number` as the password.)

When I run SYM as the logged-in user, the help icon doesn't receive focus, and when I then elevate to `root` and execute SYM the help icon didn't receive focus either, but the `welcomeDialog` **didn't** display. (Scrub the screencast to `02:13` and look at the Terminal output.)

Please confirm my current understanding: Aren't **all** scripts executed via Jamf Pro's Self Service executed as `root` ?

**Comment by bartreardon** [comment]
> Aren't all scripts executed via Jamf Pro's Self Service executed as root ?

correct, and consequently `/usr/local/bin/dialog` will be executed as root as well, but it will look after running the dialog process `/Library/Application\ Support/Dialog/Dialog.app/Contents/MacOS/Dialog` as the console user. As fas as your calling scripts are concerned you should need to worry about any of that. Just call `/usr/local/bin/dialog` and it will sort it out.

**Comment by dan-snelson** [comment]
Well, @bartreardon, now **_I'm_** not seeing `helpmessage` get focus either with [SYM 1.7.0-rc7](https://github.com/dan-snelson/dialog-scripts/blob/development/Setup%20Your%20Mac/Setup-Your-Mac-via-Dialog.bash) on a VM or physical hardware running macOS `13.2`.

<img width="932" alt="Screenshot 2023-01-25 at 7 17 52 PM" src="https://user-images.githubusercontent.com/24623109/214744813-855505a1-f08d-43e4-8f0c-f0fd0337540a.png">

Sorry to have wasted any of your cycles.

Thanks for your patience and guidance.

**Comment by bartreardon** [comment]
all good 🙂
