### ISSUE TITLE
Feature Request: Allow Title text on top of Banner Image

### ISSUE THREAD

**Issue by BigMacAdmin** [bartreardon/swiftDialog#192]
Please see this project: https://github.com/thom-bartlett/jss-filevault-reissue and the commentary in the #swiftdialog Mac Admin's slack channel with Adam and macsimus.

I would like to be able to include a Banner Image, but still have the Text data written on top of the banner. A `--titleonbanner` flag, per se. This would allow for a very nice looking title but leave it accessible for screen readers.

**Comment by drtaru** [comment]
My Take on this would be to add `--alttextbanner` which could set alt text for the banner image for screen readers but not need to actually render text.

Could possibly add `--alttext` flags to all the other screen media options.

**Comment by bartreardon** [comment]
alttext for images in general would be most beneficial. 

One to look in to. 🙂

**Comment by bartreardon** [comment]
@BigMacAdmin how does this look? Tossing up whether the argument should be `--bannertitle` or `--bannertext`, for now though, it's `--bannertitle`

## Standard behaviour:
![image](https://user-images.githubusercontent.com/3598965/204788027-9e2bd55e-ffa4-4f08-892e-e5eb1107c8ff.png)

## With `--bannertitle`

Sets the text colour to white. Will respect `--titlefont colour=...` modifications. This is because there's no direct support for light/dark mode images and so the font colour should be predictable. 

Can be used as `--bannertitle "<text>"` or as a modifier to title as `--title "<text>" --bannertitle`

![image](https://user-images.githubusercontent.com/3598965/204788173-9b8b766b-ae16-42b0-9fbc-d6f359f764a0.png)


## With `--bannertitle --titlefont shadow=true`

Since text over images doesn't always work, an option to add a drop shadow. value can be `true`, `yes`, `y`, or `1` to enable.

![image](https://user-images.githubusercontent.com/3598965/204788353-42e75f43-f2c2-4e07-aacb-564678227b8e.png)

**Comment by dan-snelson** [comment]
Looks sweet, @bartreardon.

**Comment by mm2270** [comment]
👏 👏 Very nice! I especially love the addition of being able to add a drop shadow. Good thinking ahead on that one!

**Comment by BigMacAdmin** [comment]
You've outdone yourself again,I love the look and the dropshadow option. I also love how flexible you made it with the multiple ways to call it.
