### ISSUE TITLE
Crash if icon points to unavailable http(s) url

### ISSUE THREAD

**Issue by ehemmete** [bartreardon/swiftDialog#208]
I've run into an issue where some of our Jamf self service icons have gone missing and when that happens, swiftDialog crashes when trying to display them.
Ideally it would fall back to the default icon if nothing comes down.

$ dialog --title "Title goes here" --message "Message goes here" --icon "https://www.dropbox.com/s/4batk8v5outfxo5/install.png?dl=0"
/usr/local/bin/dialog: line 2: 35600 Trace/BPT trap: 5       /Library/Application\ Support/Dialog/Dialog.app/Contents/MacOS/Dialog "$@"

**Comment by ehemmete** [comment]
Maybe the issue is that something comes down, but it is 0 bytes

**Comment by bartreardon** [comment]
ah - the reason this is failing is that the icon you are specifying is behind a redirect. swiftDialog will handle 404's and present a boxed `?` icon if it can't display the resource but I'll see what I can do about following redirects.

**Comment by bartreardon** [comment]
This issue should be fixed in [2.3](https://github.com/bartreardon/swiftDialog/releases/tag/v2.3.0) now I've moved to asynchronous image processing. Using the example command above should at worse result in a [?] icon

<img width="727" alt="image" src="https://github.com/bartreardon/swiftDialog/assets/3598965/fd92aec7-4de0-4bfd-9471-f6da3f5454ac">
