### ISSUE TITLE
Video Player Lacks Playback Controls if youtubeid Flag is Used

### ISSUE THREAD

**Issue by rougegoat** [bartreardon/swiftDialog#236]
When using the `--video youtubeid=XXXXX` feature, the video itself plays but has no player controls for things like pausing, rewinding, adjusting volume, etc.

Expected behavior: The video player plays the video and provides access to pause, volume, rewinding, etc.

Steps to reproduce:  This command reproduces the issue `dialog --video "youtubeid=MolWjT2eDuc" --autoplay --title "Test 1"
`

**Comment by bartreardon** [comment]
The `youtubeid=XXXXX` feature is just a shortcut in the `--video` argument to the full embedded youtube player URL and is convenient for quickly displaying a video with minimal fuss. As you note it has controls and info disabled and this is by design.

If you want to take full advantage of the embedded player you can just pass in the full URL yourself, e.g.
`dialog --video "https://www.youtube.com/embed/MolWjT2eDuc?controls=1&autoplay=1" --title "Test 1"`

There are other arguments you can pass in which are documented in youtube's API documentation https://developers.google.com/youtube/player_parameters
