### ISSUE TITLE
swiftDialog 2.3.0 Beta 2 - cannot control --titlefont size without adjusting --messagefont size

### ISSUE THREAD

**Issue by mm2270** [bartreardon/swiftDialog#286]
**Is your feature request related to a problem? Please describe.**
I'm not clear if this is a feature request or a bug report. I'm erring on the side that this may be by design and a FR is warranted.
When using the current beta swiftDialog 2.3.0 Beta 2, along with the new `--style alert` (or `warning`, `caution`) it doesn't seem possible to adjust the messagefont size and titlefont sizes independently. Meaning, if I add a `--titlefont "size=18"` it ignores it, but if I add `--messagefont "size=14"`, it applies that change to message font size, and ALSO adjusts the size of the title to a size that seems proportionally matched to the message font size. It still ignores what I set in `--titlefont` though, unlike with any of the other regular dialog windows (save for `--mini` of course)

Is this by design? Or is it a bug and should I be able to control both independently?

**Describe the solution you'd like**
I would like to be able to use the new style dialogs and also have more independent control over the title font style and size without it being linked to the message font size.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bartreardon** [comment]
`--style alert` is just a shortcut that pre-defines some arguments. Part of what it does is set `--title` to `none` and instead appends the title to the message area as markdown. So it's not that you can't set the size of the title, it's that there is no title.

The documentation for how it works is not yet complete but in essence,

 `--style alert --title "Title here" --message "The rest of the message here`

is the same as,

`--title none --buttonstyle centre --centreicon --message "### Title here\n\nThe rest of the message here" --iconsize 80 --messagealignment centre --width 300 --height 300`

in short - it's by design.

**Comment by mm2270** [comment]
@bartreardon Thanks for the explanation! Makes sense now. I guess I didn't really notice that the title was not really there, but now that you've pointed it out, I can see what you mean.

I guess if I wanted some more control over that, I would need to custom craft my dialog, possibly by doing something like

`dialog --title "Title here" --titlefont "size=18" --buttonstyle centre --centreicon --message "The rest of the message here" --messagefont "size=14" --messagealignment centre --width 300 --height 300 --buttonstyle centre --iconsize 64 --ontop`
